-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
<<<<<<< Updated upstream:queries/createDatabase.sql
--   at:        2022-02-24 21:54:15 CET
=======
--   at:        2022-03-04 02:15:17 CET
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE authors (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id       INTEGER NOT NULL,
=======
    id       SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id INTEGER,
    name     VARCHAR(60) NOT NULL
);

ALTER TABLE authors ADD CONSTRAINT authors_pk PRIMARY KEY ( id );

CREATE TABLE events (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id          INTEGER NOT NULL,
=======
    id          SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    playlist_id INTEGER,
    name        VARCHAR(30) NOT NULL,
    start_date  TIMESTAMP,
    end_date    TIMESTAMP,
    description text
);

COMMENT ON COLUMN events.description IS
    'text';

ALTER TABLE events ADD CONSTRAINT events_pk PRIMARY KEY ( id );

CREATE TABLE permissions (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id   INTEGER NOT NULL,
=======
    id   SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    name VARCHAR(50) NOT NULL
);

ALTER TABLE permissions ADD CONSTRAINT permissions_pk PRIMARY KEY ( id );

CREATE TABLE playlist_elements (
    playlist_id INTEGER NOT NULL,
    "Order"     INTEGER NOT NULL,
    song_id     INTEGER,
    sets_id     INTEGER,
    played      CHAR(1) NOT NULL
);

ALTER TABLE playlist_elements
    ADD CONSTRAINT fkarc_2 CHECK ( ( ( sets_id IS NOT NULL )
                                     AND ( song_id IS NULL ) )
                                   OR ( ( song_id IS NOT NULL )
                                        AND ( sets_id IS NULL ) )
                                   OR ( ( sets_id IS NULL )
                                        AND ( song_id IS NULL ) ) );

ALTER TABLE playlist_elements ADD CONSTRAINT playlist_elements_pk PRIMARY KEY ( playlist_id,
                                                                                "Order" );

CREATE TABLE playlists (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id       INTEGER NOT NULL,
=======
    id       SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id INTEGER NOT NULL
);

ALTER TABLE playlists ADD CONSTRAINT playlists_pk PRIMARY KEY ( id );

CREATE TABLE roles (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id   INTEGER NOT NULL,
=======
    id   SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    name VARCHAR(50) NOT NULL
);

ALTER TABLE roles ADD CONSTRAINT roles_pk PRIMARY KEY ( id );

CREATE TABLE roles_permissions (
    permissions_id INTEGER NOT NULL,
    roles_id       INTEGER NOT NULL
);

ALTER TABLE roles_permissions ADD CONSTRAINT roles_permissions_pk PRIMARY KEY ( permissions_id,
                                                                                roles_id );

CREATE TABLE set_elements (
    sets_id INTEGER NOT NULL,
    "Order" INTEGER NOT NULL,
    song_id INTEGER NOT NULL
);

ALTER TABLE set_elements ADD CONSTRAINT set_elements_pk PRIMARY KEY ( sets_id,
                                                                      "Order" );

CREATE TABLE sets (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id       INTEGER NOT NULL,
=======
    id       SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id INTEGER NOT NULL,
    name     VARCHAR(30) NOT NULL,
    color    CHAR(7) NOT NULL
);

COMMENT ON COLUMN sets.name IS
    'optional';

COMMENT ON COLUMN sets.color IS
    'optional';

ALTER TABLE sets ADD CONSTRAINT sets_pk PRIMARY KEY ( id );

CREATE TABLE song_transitions (
    pervious_song_id INTEGER NOT NULL,
    next_song_id     INTEGER NOT NULL,
    power            INTEGER NOT NULL,
    created_manualy  CHAR(1) NOT NULL
);

COMMENT ON COLUMN song_transitions.power IS
    'integer';

COMMENT ON COLUMN song_transitions.created_manualy IS
    'boolean';

ALTER TABLE song_transitions ADD CONSTRAINT song_transitions_pk PRIMARY KEY ( pervious_song_id,
                                                                              next_song_id );

CREATE TABLE songs (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id              INTEGER NOT NULL,
=======
    id              SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id        INTEGER NOT NULL,
    title           VARCHAR(30) NOT NULL,
    album           VARCHAR(30),
    date_of_release DATE,
    bpm             FLOAT NOT NULL,
    lyrics          text,
    sheet_music     text,
    mp3             varchar,
    length          SMALLINT
);

COMMENT ON COLUMN songs.length IS
    'Min:Secs';

ALTER TABLE songs ADD CONSTRAINT songs_pk PRIMARY KEY ( id );

CREATE TABLE songs_authors (
    songs_id   INTEGER NOT NULL,
    authors_id INTEGER NOT NULL
);

ALTER TABLE songs_authors ADD CONSTRAINT songs_authors_pk PRIMARY KEY ( songs_id,
                                                                        authors_id );

CREATE TABLE songs_tags (
    songs_id INTEGER NOT NULL,
    tags_id  INTEGER NOT NULL
);

ALTER TABLE songs_tags ADD CONSTRAINT songs_tags_pk PRIMARY KEY ( songs_id,
                                                                  tags_id );

CREATE TABLE tag_groups (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id       INTEGER NOT NULL,
=======
    id       SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id INTEGER NOT NULL,
    name     VARCHAR(30) NOT NULL,
    color    CHAR(7) NOT NULL
);

ALTER TABLE tag_groups ADD CONSTRAINT tag_groups_pk PRIMARY KEY ( id );

CREATE TABLE tags (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id            INTEGER NOT NULL,
=======
    id            SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    tag_groups_id INTEGER,
    users_id      INTEGER,
    name          VARCHAR(15) NOT NULL
);

ALTER TABLE tags ADD CONSTRAINT tags_pk PRIMARY KEY ( id );

CREATE TABLE users (
<<<<<<< Updated upstream:queries/createDatabase.sql
    id       INTEGER NOT NULL,
=======
    id       SERIAL NOT NULL,
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    email    VARCHAR(50) NOT NULL,
    password CHAR(64) NOT NULL,
    name     VARCHAR(30) NOT NULL
);

COMMENT ON COLUMN users.password IS
    'HASH';

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( id );

<<<<<<< Updated upstream:queries/createDatabase.sql
CREATE TABLE users_permisions (
=======
CREATE TABLE users_permissions (
>>>>>>> Stashed changes:gig_planner/lib/queries/createTables.sql
    users_id       INTEGER NOT NULL,
    events_id      INTEGER NOT NULL,
    permissions_id INTEGER NOT NULL
);

ALTER TABLE users_permissions
    ADD CONSTRAINT users_permissions_pk PRIMARY KEY ( events_id,
                                                      permissions_id,
                                                      users_id );

ALTER TABLE authors
    ADD CONSTRAINT authors_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE events
    ADD CONSTRAINT events_playlists_fk FOREIGN KEY ( playlist_id )
        REFERENCES playlists ( id );

ALTER TABLE playlist_elements
    ADD CONSTRAINT playlist_elements_playlists_fk FOREIGN KEY ( playlist_id )
        REFERENCES playlists ( id );

ALTER TABLE playlist_elements
    ADD CONSTRAINT playlist_elements_sets_fk FOREIGN KEY ( sets_id )
        REFERENCES sets ( id );

ALTER TABLE playlist_elements
    ADD CONSTRAINT playlist_elements_songs_fk FOREIGN KEY ( song_id )
        REFERENCES songs ( id );

ALTER TABLE playlists
    ADD CONSTRAINT playlists_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE roles_permissions
    ADD CONSTRAINT roles_permissions_permissions_fk FOREIGN KEY ( permissions_id )
        REFERENCES permissions ( id );

ALTER TABLE roles_permissions
    ADD CONSTRAINT roles_permissions_roles_fk FOREIGN KEY ( roles_id )
        REFERENCES roles ( id );

ALTER TABLE set_elements
    ADD CONSTRAINT set_elements_sets_fk FOREIGN KEY ( sets_id )
        REFERENCES sets ( id );

ALTER TABLE set_elements
    ADD CONSTRAINT set_elements_songs_fk FOREIGN KEY ( song_id )
        REFERENCES songs ( id );

ALTER TABLE sets
    ADD CONSTRAINT sets_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE song_transitions
    ADD CONSTRAINT song_transitions_songs_next FOREIGN KEY ( next_song_id )
        REFERENCES songs ( id );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE song_transitions
    ADD CONSTRAINT song_transitions_songs_pervious FOREIGN KEY ( pervious_song_id )
        REFERENCES songs ( id );

ALTER TABLE songs_authors
    ADD CONSTRAINT songs_authors_authors_fk FOREIGN KEY ( authors_id )
        REFERENCES authors ( id );

ALTER TABLE songs_authors
    ADD CONSTRAINT songs_authors_songs_fk FOREIGN KEY ( songs_id )
        REFERENCES songs ( id );

ALTER TABLE songs_tags
    ADD CONSTRAINT songs_tags_songs_fk FOREIGN KEY ( songs_id )
        REFERENCES songs ( id );

ALTER TABLE songs_tags
    ADD CONSTRAINT songs_tags_tags_fk FOREIGN KEY ( tags_id )
        REFERENCES tags ( id );

ALTER TABLE songs
    ADD CONSTRAINT songs_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE tag_groups
    ADD CONSTRAINT tag_groups_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE tags
    ADD CONSTRAINT tags_tag_groups_fk FOREIGN KEY ( tag_groups_id )
        REFERENCES tag_groups ( id );

ALTER TABLE tags
    ADD CONSTRAINT tags_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );

ALTER TABLE users_permissions
    ADD CONSTRAINT users_permissions_events_fk FOREIGN KEY ( events_id )
        REFERENCES events ( id );

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE users_permissions
    ADD CONSTRAINT users_permissions_permissions_fk FOREIGN KEY ( permissions_id )
        REFERENCES permissions ( id );

ALTER TABLE users_permissions
    ADD CONSTRAINT users_permissions_users_fk FOREIGN KEY ( users_id )
        REFERENCES users ( id );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             42
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   3
-- WARNINGS                                 0
